sampling:
  - no_sample: True
    history: 1
memory: 
  - type: 'node'
    dim_time: 100
    deliver_to: 'self'
    mail_combine: 'last'
    memory_update: 'rnn'
    mailbox_size: 1
    combine_node_feature: True
    dim_out: 100
gnn:
  - arch: 'identity'
    time_transform: 'JODIE'
train:
  - epoch: 100
    batch_size: 600
    lr: 0.0001
    dropout: 0.1
    all_on_gpu: True